
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Mar 31 20:42:02 CEST 2024
//----------------------------------------------------

package main.sintactico;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int FAKE = 49;
  public static final int REGISTRO = 9;
  public static final int DIVER = 8;
  public static final int DOSPUNTOS = 38;
  public static final int INCOGNITO = 11;
  public static final int POT = 16;
  public static final int LLCIERRE = 46;
  public static final int CCIERRE = 42;
  public static final int PCIERRE = 44;
  public static final int CONJ = 29;
  public static final int ENTERO = 47;
  public static final int SI = 4;
  public static final int RESTA = 21;
  public static final int CAP = 41;
  public static final int PUNTOCOMA = 36;
  public static final int TRAFICAR = 13;
  public static final int MENORIGUAL = 27;
  public static final int IGUAL = 22;
  public static final int SINO = 5;
  public static final int DEVUELVE = 12;
  public static final int LLAP = 45;
  public static final int MIENTRAS = 6;
  public static final int DIV = 18;
  public static final int COMO = 14;
  public static final int SUMA = 20;
  public static final int DISY = 30;
  public static final int MAYORIGUAL = 26;
  public static final int EOF = 0;
  public static final int FACTO = 48;
  public static final int error = 1;
  public static final int NULO = 50;
  public static final int COMA = 35;
  public static final int MUL = 17;
  public static final int MENOS = 40;
  public static final int MENOR = 25;
  public static final int MOD = 19;
  public static final int DIRECCION = 31;
  public static final int PUNTERO = 32;
  public static final int DESIGUAL = 23;
  public static final int VECTOR = 10;
  public static final int ASIGNACION = 33;
  public static final int MAYOR = 24;
  public static final int NUEVO = 15;
  public static final int ENT = 2;
  public static final int PAP = 43;
  public static final int FLECHA = 39;
  public static final int NEG = 28;
  public static final int BIN = 3;
  public static final int RUTA = 52;
  public static final int PUNTO = 34;
  public static final int IDEN = 51;
  public static final int CUATROPUNTOS = 37;
  public static final int PARA = 7;
}

