
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Feb 22 16:43:22 CET 2024
//----------------------------------------------------

package main.sintactico;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
	/* terminals */
	public static final int FAKE = 5;
	public static final int REGISTRO = 11;
	public static final int DIVER = 10;
	public static final int DOSPUNTOS = 38;
	public static final int INCOGNITO = 12;
	public static final int POT = 17;
	public static final int LLCIERRE = 45;
	public static final int CCIERRE = 41;
	public static final int PCIERRE = 43;
	public static final int CONJ = 30;
	public static final int ENTERO = 16;
	public static final int SI = 6;
	public static final int RESTA = 22;
	public static final int CAP = 40;
	public static final int PUNTOCOMA = 37;
	public static final int TRAFICAR = 14;
	public static final int MENORIGUAL = 28;
	public static final int IGUAL = 23;
	public static final int SINO = 7;
	public static final int DEVUELVE = 13;
	public static final int LLAP = 44;
	public static final int MIENTRAS = 8;
	public static final int DIV = 19;
	public static final int SUMA = 21;
	public static final int DISY = 31;
	public static final int ID = 15;
	public static final int MAYORIGUAL = 27;
	public static final int EOF = 0;
	public static final int FACTO = 4;
	public static final int error = 1;
	public static final int COMA = 36;
	public static final int MUL = 18;
	public static final int MENOR = 26;
	public static final int MOD = 20;
	public static final int DIRECCION = 32;
	public static final int PUNTERO = 33;
	public static final int DESIGUAL = 24;
	public static final int ASIGNACION = 34;
	public static final int MAYOR = 25;
	public static final int ENT = 2;
	public static final int PAP = 42;
	public static final int FLECHA = 39;
	public static final int NEG = 29;
	public static final int BIN = 3;
	public static final int PUNTO = 35;
	public static final int PARA = 9;
}
