
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Feb 26 19:24:26 CET 2024
//----------------------------------------------------

package main.sintactico;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
	/* terminals */
	public static final int FAKE = 5;
	public static final int REGISTRO = 11;
	public static final int DIVER = 10;
	public static final int DOSPUNTOS = 40;
	public static final int INCOGNITO = 13;
	public static final int POT = 19;
	public static final int LLCIERRE = 47;
	public static final int CCIERRE = 43;
	public static final int PCIERRE = 45;
	public static final int CONJ = 32;
	public static final int ENTERO = 18;
	public static final int SI = 6;
	public static final int RESTA = 24;
	public static final int CAP = 42;
	public static final int PUNTOCOMA = 39;
	public static final int TRAFICAR = 15;
	public static final int MENORIGUAL = 30;
	public static final int IGUAL = 25;
	public static final int SINO = 7;
	public static final int DEVUELVE = 14;
	public static final int LLAP = 46;
	public static final int MIENTRAS = 8;
	public static final int DIV = 21;
	public static final int COMO = 16;
	public static final int SUMA = 23;
	public static final int DISY = 33;
	public static final int IDEN = 17;
	public static final int MAYORIGUAL = 29;
	public static final int EOF = 0;
	public static final int FACTO = 4;
	public static final int error = 1;
	public static final int COMA = 38;
	public static final int MUL = 20;
	public static final int NULO = 12;
	public static final int MENOR = 28;
	public static final int MOD = 22;
	public static final int DIRECCION = 34;
	public static final int PUNTERO = 35;
	public static final int DESIGUAL = 26;
	public static final int ASIGNACION = 36;
	public static final int MAYOR = 27;
	public static final int ENT = 2;
	public static final int PAP = 44;
	public static final int FLECHA = 41;
	public static final int NEG = 31;
	public static final int BIN = 3;
	public static final int PUNTO = 37;
	public static final int PARA = 9;
}
