
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Apr 15 11:40:15 CEST 2024
//----------------------------------------------------

package main.java.sintactico;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int FAKE = 57;
  public static final int REGISTRO = 9;
  public static final int DIVER = 8;
  public static final int DOSPUNTOS = 46;
  public static final int INCOGNITO = 11;
  public static final int POT = 24;
  public static final int LLCIERRE = 54;
  public static final int CCIERRE = 50;
  public static final int PCIERRE = 52;
  public static final int CONJ = 37;
  public static final int ENTERO = 55;
  public static final int SI = 4;
  public static final int SUMAASIG = 20;
  public static final int RESTA = 29;
  public static final int CAP = 49;
  public static final int PUNTOCOMA = 44;
  public static final int TRAFICAR = 13;
  public static final int MENORIGUAL = 35;
  public static final int IGUAL = 30;
  public static final int SINO = 5;
  public static final int DEVUELVE = 12;
  public static final int LLAP = 53;
  public static final int MIENTRAS = 6;
  public static final int DIV = 26;
  public static final int COMO = 14;
  public static final int SUMA = 28;
  public static final int DISY = 38;
  public static final int MAYORIGUAL = 34;
  public static final int DISYASIG = 23;
  public static final int POTASIG = 16;
  public static final int EOF = 0;
  public static final int FACTO = 56;
  public static final int error = 1;
  public static final int NULO = 58;
  public static final int COMA = 43;
  public static final int MUL = 25;
  public static final int MENOS = 48;
  public static final int MENOR = 33;
  public static final int MOD = 27;
  public static final int DIRECCION = 39;
  public static final int RESTAASIG = 21;
  public static final int PUNTERO = 40;
  public static final int DESIGUAL = 31;
  public static final int VECTOR = 10;
  public static final int ASIGNACION = 41;
  public static final int MAYOR = 32;
  public static final int NUEVO = 15;
  public static final int ENT = 2;
  public static final int PAP = 51;
  public static final int FLECHA = 47;
  public static final int NEG = 36;
  public static final int BIN = 3;
  public static final int RUTA = 60;
  public static final int PUNTO = 42;
  public static final int MULASIG = 17;
  public static final int IDEN = 59;
  public static final int CUATROPUNTOS = 45;
  public static final int DIVASIG = 18;
  public static final int MODASIG = 19;
  public static final int PARA = 7;
  public static final int CONJASIG = 22;
}

