
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Feb 17 20:51:55 CET 2024
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 19;
  public static final int MENOS = 10;
  public static final int MENOR = 13;
  public static final int CONCATENACION = 17;
  public static final int IGUAL = 15;
  public static final int DESIGUAL = 16;
  public static final int IDEN = 6;
  public static final int CCIERRE = 21;
  public static final int LMAP = 4;
  public static final int POR = 11;
  public static final int CAP = 20;
  public static final int COMA = 23;
  public static final int ASIGNACION = 22;
  public static final int MAYOR = 14;
  public static final int EOF = 0;
  public static final int LFILTER = 3;
  public static final int LREDUCE = 5;
  public static final int DIV = 12;
  public static final int PAP = 18;
  public static final int PRINT = 2;
  public static final int error = 1;
  public static final int REAL = 8;
  public static final int ENT = 7;
  public static final int MAS = 9;
}

